# Generated by Django 3.2.5 on 2021-09-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_user'),
        ('customers', '0002_auto_20210804_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sus_end',
            new_name='suspend_end',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sus_start',
            new_name='suspend_start',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='one_time_pickup',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reg_pickup',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='suspension',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='pickup_day',
            field=models.CharField(default='Monday', max_length=9),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Onetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onetime_pickup_date', models.DateField(editable=False)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
        ),
    ]
