# Generated by Django 3.2.7 on 2021-09-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210924_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Onetime',
            new_name='Special_pickups',
        ),
        migrations.RenameField(
            model_name='special_pickups',
            old_name='onetime_pickup_date',
            new_name='special_pickup_date',
        ),
    ]
